name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore source/EduCATS.sln

    - name: Build
      run: msbuild source/EduCATS.sln /t:PackageForAndroid
